# Generated by Django 2.2.16 on 2020-09-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155, verbose_name='Имя')),
                ('surname', models.CharField(max_length=155, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=155, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('bio', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_finish', models.DateTimeField(verbose_name='Дата завершения')),
                ('early_count', models.IntegerField(default=0, verbose_name='Голоса для для победы')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('persons', models.ManyToManyField(related_name='votings', to='voting.Persona')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.Persona')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting')),
            ],
        ),
    ]
