# Generated by Django 2.2.16 on 2020-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='winner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Победитель'),
        ),
    ]
